name: attribution
channels:
  - nvidia/label/cuda-12.2.0
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=1.4.0=py38h06a4308_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - async-timeout=4.0.3=py38h06a4308_0
  - blas=1.0=mkl
  - blinker=1.6.2=py38h06a4308_0
  - bottleneck=1.3.4=py38hce1f21e_0
  - brotli=1.0.9=he6710b0_2
  - brotli-python=1.0.9=py38heb0550a_2
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2024.8.30=py38h06a4308_0
  - cffi=1.15.0=py38hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py38h06a4308_0
  - cryptography=41.0.3=py38h130f0dd_0
  - cuda-cccl=12.2.53=0
  - cuda-command-line-tools=12.2.0=0
  - cuda-compiler=12.2.0=0
  - cuda-cudart=12.2.53=0
  - cuda-cudart-dev=12.2.53=0
  - cuda-cudart-static=12.2.53=0
  - cuda-cuobjdump=12.2.53=0
  - cuda-cupti=12.2.60=0
  - cuda-cupti-static=12.2.60=0
  - cuda-cuxxfilt=12.2.53=0
  - cuda-documentation=12.2.53=0
  - cuda-driver-dev=12.2.53=0
  - cuda-gdb=12.2.53=0
  - cuda-libraries=12.2.0=0
  - cuda-libraries-dev=12.2.0=0
  - cuda-libraries-static=12.2.0=0
  - cuda-nsight=12.2.53=0
  - cuda-nsight-compute=12.2.0=0
  - cuda-nvcc=12.2.91=0
  - cuda-nvdisasm=12.2.53=0
  - cuda-nvml-dev=12.2.81=0
  - cuda-nvprof=12.2.60=0
  - cuda-nvprune=12.2.53=0
  - cuda-nvrtc=12.2.91=0
  - cuda-nvrtc-dev=12.2.91=0
  - cuda-nvrtc-static=12.2.91=0
  - cuda-nvtx=12.2.53=0
  - cuda-nvvp=12.2.60=0
  - cuda-opencl=12.2.53=0
  - cuda-opencl-dev=12.2.53=0
  - cuda-profiler-api=12.2.53=0
  - cuda-sanitizer-api=12.2.53=0
  - cuda-toolkit=12.2.0=0
  - cuda-tools=12.2.0=0
  - cuda-visual-tools=12.2.0=0
  - cudatoolkit=11.0.221=h6bb024c_0
  - freetype=2.11.0=h70c0345_0
  - frozenlist=1.2.0=py38h7f8727e_0
  - gds-tools=1.7.0.149=0
  - giflib=5.2.1=h7b6447c_0
  - git-lfs=3.6.1=he404d97_0
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - grpcio=1.42.0=py38hce63b2e_0
  - idna=3.4=py38h06a4308_0
  - importlib-metadata=7.0.1=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h7f8727e_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libcublas=12.2.1.16=0
  - libcublas-dev=12.2.1.16=0
  - libcublas-static=12.2.1.16=0
  - libcufft=11.0.8.15=0
  - libcufft-dev=11.0.8.15=0
  - libcufft-static=11.0.8.15=0
  - libcufile=1.7.0.149=0
  - libcufile-dev=1.7.0.149=0
  - libcufile-static=1.7.0.149=0
  - libcurand=10.3.3.53=0
  - libcurand-dev=10.3.3.53=0
  - libcurand-static=10.3.3.53=0
  - libcusolver=11.5.0.53=0
  - libcusolver-dev=11.5.0.53=0
  - libcusolver-static=11.5.0.53=0
  - libcusparse=12.1.1.53=0
  - libcusparse-dev=12.1.1.53=0
  - libcusparse-static=12.1.1.53=0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libnpp=12.1.1.14=0
  - libnpp-dev=12.1.1.14=0
  - libnpp-static=12.1.1.14=0
  - libnvjitlink=12.2.91=0
  - libnvjitlink-dev=12.2.91=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libnvjpeg-static=12.1.1.14=0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.20.1=h4ff587b_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.2.0=h2818925_1
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - markdown=3.4.1=py38h06a4308_0
  - markupsafe=2.1.1=py38h7f8727e_0
  - matplotlib-base=3.5.1=py38ha18d171_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - multidict=5.2.0=py38h7f8727e_2
  - munkres=1.1.4=py_0
  - ncurses=6.3=h7f8727e_2
  - nsight-compute=2023.2.0.16=0
  - numpy=1.22.3=py38he7a7128_0
  - numpy-base=1.22.3=py38hf524024_0
  - oauthlib=3.2.2=py38h06a4308_0
  - openssl=1.1.1w=h7f8727e_0
  - plotly=5.24.1=py38h2f386ee_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py38h06a4308_0
  - pyopenssl=23.2.0=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - pytz=2024.1=py38h06a4308_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.31.0=py38h06a4308_1
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - seaborn=0.13.2=py38h06a4308_0
  - setuptools=68.2.2=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.5=hc218d9a_0
  - tenacity=9.0.0=py38h06a4308_0
  - tensorboard=2.11.0=py38h06a4308_0
  - tensorboard-data-server=0.6.0=py38hca6d32c_0
  - tensorboard-plugin-wit=1.8.1=py38h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - werkzeug=2.2.3=py38h06a4308_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.2.5=h7f8727e_1
  - yarl=1.6.3=py38h27cfd23_0
  - zipp=3.17.0=py38h06a4308_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - accelerate==0.27.2
      - aclpubcheck==0.1
      - aiodns==3.2.0
      - aiofiles==23.2.1
      - aiohttp==3.10.11
      - alias==0.3.10
      - alpaca-trade-api==3.2.0
      - altair==5.4.1
      - annotated-types==0.7.0
      - ansicolors==1.1.8
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - argparse==1.4.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==25.3.0
      - babel==2.15.0
      - backcall==0.2.0
      - bcrypt==4.2.1
      - beartype==0.17.2
      - beautifulsoup4==4.12.3
      - bertviz==1.4.0
      - bibtexparser==1.4.1
      - bitsandbytes==0.42.0
      - bleach==6.1.0
      - boto3==1.35.45
      - botocore==1.35.45
      - cchardet==2.1.7
      - ccxt==4.4.86
      - cfgv==3.4.0
      - chardet==5.2.0
      - colorama==0.4.4
      - colossalai==0.3.4
      - comm==0.2.2
      - contexttimer==0.3.3
      - contourpy==1.1.1
      - cssselect==1.2.0
      - cycler==0.12.1
      - dataproperty==1.0.1
      - datasets==2.17.0
      - debugpy==1.8.2
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - dill==0.3.8
      - distlib==0.3.9
      - distro==1.9.0
      - django==4.2.13
      - docstring-parser==0.15
      - einx==0.3.0
      - entrypoints==0.4
      - evaluate==0.4.1
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fabric==3.2.2
      - fairscale==0.4.13
      - fastapi==0.112.1
      - fastjsonschema==2.20.0
      - ffmpy==0.4.0
      - filelock==3.13.1
      - fire==0.6.0
      - flake8==7.1.2
      - fonttools==4.47.2
      - fqdn==1.5.1
      - frozendict==2.4.6
      - fsspec==2023.10.0
      - ftfy==6.2.3
      - future==0.18.3
      - google==3.0.0
      - gradio==3.50.2
      - gradio-client==0.6.1
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.27.0
      - hypothesis==6.91.0
      - identify==2.6.1
      - ijson==3.3.0
      - importlib-resources==6.1.1
      - invoke==2.2.0
      - ipykernel==6.29.4
      - ipython==8.12.3
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.3
      - jiter==0.9.1
      - jmespath==1.0.1
      - joblib==1.3.2
      - json5==0.9.25
      - jsonlines==4.0.0
      - jsonschema==4.23.0
      - jupyter==1.0.0
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.11
      - kaleido==0.2.1
      - keycache==0.27.0
      - kiwisolver==1.4.5
      - latexcodec==3.0.0
      - libcst==1.1.0
      - lion-pytorch==0.1.2
      - lm-eval==0.4.3
      - loguru==0.7.3
      - lxml==5.2.2
      - matplotlib==3.7.4
      - matplotlib-inline==0.1.7
      - mbstrdecoder==1.1.3
      - mccabe==0.7.0
      - mistune==3.0.2
      - modelscope==1.24.1
      - monotonic==1.6
      - more-itertools==10.3.0
      - msgpack==1.0.3
      - multiprocess==0.70.16
      - narwhals==1.17.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - ninja==1.11.1.4
      - nltk==3.8.1
      - nodeenv==1.9.1
      - notebook==7.2.1
      - notebook-shim==0.2.4
      - numexpr==2.8.6
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-nccl-cu12==2.18.1
      - openai==0.28.0
      - opencv-python==4.10.0.84
      - orjson==3.10.7
      - packaging==23.2
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - papermill==2.6.0
      - paramiko==3.5.1
      - parso==0.8.4
      - pathvalidate==3.2.0
      - pdfminer-six==20231228
      - pdfplumber==0.11.4
      - pdfquery==0.4.3
      - peft==0.9.0
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - pip==25.0.1
      - platformdirs==4.2.2
      - pluggy==0.13.1
      - portalocker==2.10.1
      - pre-commit==3.5.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - protobuf==4.25.7
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyaescrypt==6.1.1
      - pyarrow==15.0.0
      - pyarrow-hotfix==0.6
      - pybind11==2.13.1
      - pybtex==0.24.0
      - pycares==4.4.0
      - pycodestyle==2.12.1
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydub==0.25.1
      - pyexecjs==1.5.1
      - pyflakes==3.2.0
      - pygments==2.17.2
      - pylatexenc==2.10
      - pynacl==1.5.0
      - pyparsing==3.1.1
      - pypdfium2==4.30.0
      - pyquery==2.0.1
      - pytablewriter==1.2.0
      - pytesseract==0.3.13
      - pytest==8.0.2
      - python-dateutil==2.8.2
      - python-docx==1.1.2
      - python-dotenv==0.19.2
      - python-json-logger==2.0.7
      - python-multipart==0.0.9
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - ray==2.10.0
      - rebiber==1.1.3
      - regex==2023.12.25
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.0
      - roman==4.2
      - rouge-score==0.1.2
      - rpds-py==0.18.1
      - ruff==0.6.1
      - s3transfer==0.10.2
      - sacrebleu==2.4.2
      - safetensors==0.4.2
      - scikit-learn==1.3.2
      - scipy==1.9.3
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - shtab==1.7.1
      - skypilot==0.4.1
      - soupsieve==2.5
      - sqlitedict==2.1.0
      - sqlparse==0.5.0
      - stack-data==0.6.3
      - standalone==1.0.1
      - starlette==0.38.2
      - streetlevel==0.5.0
      - swarms==2.4.4
      - sympy==1.12
      - tabledata==1.3.3
      - tabulate==0.9.0
      - tcolorpy==0.1.6
      - terminado==0.18.1
      - tesseract==0.1.3
      - threadpoolctl==3.3.0
      - tiktoken==0.6.0
      - timm==0.9.16
      - tinycss2==1.3.0
      - tokenizers==0.20.3
      - tomli==2.0.1
      - tomlkit==0.12.0
      - torch==2.1.1
      - torchaudio==2.1.1
      - torchfix==0.3.0
      - torchvision==0.16.1
      - tornado==6.4.1
      - tqdm==4.66.2
      - tqdm-multiprocess==0.0.11
      - traitlets==5.14.3
      - transformers==4.46.3
      - triton==2.1.0
      - trl==0.7.11
      - tsv==1.2
      - typepy==1.3.2
      - typer==0.12.4
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.13.2
      - tyro==0.7.3
      - tzdata==2024.1
      - ujson==5.10.0
      - unidecode==1.3.8
      - unzip==1.0.0
      - uri-template==1.3.0
      - urllib3==1.26.20
      - uvicorn==0.30.6
      - v20==3.0.25.0
      - vector-quantize-pytorch==1.14.1
      - virtualenv==20.30.0
      - wand==0.6.13
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websockets==10.4
      - widgetsnbextension==4.0.11
      - word2number==1.1
      - xxhash==3.4.1
      - zetascale==2.2.7
      - zstandard==0.23.0
